### ISSUE TITLE
use_x_forwarded_for enforced in HA 2021.7

### ISSUE THREAD

**Issue by eglia** [BeryJu/hass-auth-header#38]
Starting with HomeAssistant 2021.7, the use of use_x_forwarded_for will be enforced if behind a reverse proxy (see release notes of [2021.6](https://www.home-assistant.io/blog/2021/06/02/release-20216/#other-breaking-changes)). This, however, conflicts with this component.
HA 2021.6 logs this warning:
` A request from a reverse proxy was received from x.x.x.x, but your HTTP integration is not set-up for reverse proxies; This request will be blocked in Home Assistant 2021.7 unless you configure your HTTP integration to allow this header`

**Comment by BeryJu** [comment]
Thanks for the warning, I don't really keep up with the HomeAssistant changelogs.

The only reason I've had the recommendation in the readme to turn `use_x_forwarded_for` off is because, as the setting is documented, when you have `use_x_forwarded_for` on, I get the IP of the actual client, not the reverse proxy. This means I can't check if the reverse proxy that sends the request is in `trusted_proxies`.
